ALTER TABLE streams ADD COLUMN IF NOT EXISTS bitrate INT NOT NULL DEFAULT 64000;
ALTER TABLE streams ADD COLUMN IF NOT EXISTS user_limit INT NOT NULL DEFAULT 0;
ALTER TABLE streams ADD COLUMN IF NOT EXISTS region VARCHAR(32) NOT NULL DEFAULT '';
