-- +goose Up
ALTER TABLE streams ADD COLUMN IF NOT EXISTS bitrate INT NOT NULL DEFAULT 64000;
ALTER TABLE streams ADD COLUMN IF NOT EXISTS user_limit INT NOT NULL DEFAULT 0;
ALTER TABLE streams ADD COLUMN IF NOT EXISTS region VARCHAR(32) NOT NULL DEFAULT '';

-- +goose Down
ALTER TABLE streams DROP COLUMN IF EXISTS region;
ALTER TABLE streams DROP COLUMN IF EXISTS user_limit;
ALTER TABLE streams DROP COLUMN IF EXISTS bitrate;
